name: Publish RubyGem
on:
  workflow_call:
    inputs:
      release_name:
        description: 'Name of the GitHub release (example: v1.0.0)'
        required: false
        type: string

  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of the GitHub release (example: v1.0.0)'
        required: false
        type: string

jobs:
  rubygem-publish:
    name: Trigger RubyGem publication
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Trigger Publish
        run: ./.ci/publish "${RELEASE_NAME}"
        env:
          RELEASE_NAME: ${{ inputs.release_name }}
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
