name: Release vagrant_cloud RubyGem

on:
  push:
    branches:
      - 'release-*'
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish vagrant_cloud RubyGem
    if: github.repository == 'hashicorp/vagrant_cloud-builder'
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
          secrets:
            kv/data/github/hashicorp/vagrant_cloud-builder rubygems_api_key;
            kv/data/teams/vagrant/slack webhook;
      - name: Code Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup Ruby
        uses: ruby/setup-ruby@922ebc4c5262cd14e07bb0e1db020984b6c064fe # v1.226.0
        with:
          ruby-version: 3.1
      - name: Publish
        run: ./.ci/publish
        env:
          RUBYGEMS_API_KEY: ${{ steps.secrets.outputs.rubygems_api_key }}
          GEM_HOST_API_KEY: ${{ steps.secrets.outputs.rubygems_api_key }}
          SLACK_WEBHOOK: ${{ steps.secrets.outputs.webhook }}
