name: Release vagrant_cloud RubyGem

on:
  push:
    branches:
      - 'release-*'
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish vagrant_cloud RubyGem
    if: github.repository == 'hashicorp/vagrant_cloud-builder'
    runs-on: ['self-hosted', 'ondemand', 'linux', 'type=t3.small']
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Authentication
        id: vault-auth
        run: vault-auth
      - name: Secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ steps.vault-auth.outputs.addr }}
          caCertificate: ${{ steps.vault-auth.outputs.ca_certificate }}
          token: ${{ steps.vault-auth.outputs.token }}
        secrets:
          kv/data/teams/vagrant/gems/rubygems_api_key;
          kv/data/teams/vagrant/slack/webhook slack_webhook;
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Publish
        run: ./.ci/publish
        env:
          RUBYGEMS_API_KEY: ${{ steps.secrets.outputs.rubygems_api_key }}
          SLACK_WEBHOOK: ${{ steps.secrets.outputs.slack_webhook }}
