name: Repository Code Sync
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  sync-builders:
    if: github.repository == 'hashicorp/vagrant_cloud'
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Sync Builder Repository
        run: ./.ci/sync
        working-directory: ${{github.workspace}}
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          HASHIBOT_USERNAME: ${{ vars.HASHIBOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
