name: Repository Code Sync
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  sync-builder:
    name: Sync builder repository
    if: github.repository == 'hashicorp/vagrant_cloud'
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Sync Builder Repository
        run: ./.ci/sync
        working-directory: ${{github.workspace}}
        env:
          HASHIBOT_TOKEN: ${{ secrets.HASHIBOT_TOKEN }}
          HASHIBOT_USERNAME: ${{ vars.HASHIBOT_USERNAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
