on:
  push:
    branches:
      - main
      - 'test-*'
    paths:
      - 'lib/**'
      - 'spec/**'
  pull_request:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'spec/**'

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ '2.5.x', '2.6.x', '2.7.x', '3.0.x' ]
    name: Vagrant Cloud unit tests on Ruby ${{ matrix.ruby }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          architecture: 'x64'
      - name: Run Tests
        run: .ci/test.sh
