name: Vagrant Cloud Unit Tests
on:
  push:
    branches:
      - main
      - 'test-*'
    paths:
      - 'lib/**'
      - 'spec/**'
  pull_request:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'spec/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.1', '3.2', '3.3' ]
    name: Vagrant Cloud unit tests on Ruby ${{ matrix.ruby }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Setup Ruby
        uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939 # v1.152.0
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true
      - name: Run Tests
        run: bundle exec rake
